### ISSUE TITLE
3 feature branches: 2 passing, 1 failing

### ISSUE THREAD

**Issue by borjaburgos** [scope-demo-app/javascript-demo-app#53]
Out of the 3 feature branches, have only of them in failing state.

**Comment by juan-fernandez** [comment]
Already the case https://app.scope.dev/dashboard/f0a213f0-b550-4bb0-a651-c1d5b9eff041/50bc7622-9b17-4cde-a936-bb4cdd02d522/default/explore/?tab=branches
