### ISSUE TITLE
Add more dummy tests to better fill the TEST DURATION HISTOGRAM

### ISSUE THREAD

**Issue by borjaburgos** [scope-demo-app/javascript-demo-app#56]

**Comment by borjaburgos** [comment]
Add an identifier to "dummy" tests. As such, this project would have:

- a very limited amount of "demo" tests (1-5)
- a lot of "dummy" tests (~1000s)
- any other test that may not be dummy tests, but still not interesting enough to be highlighted as "demo"

Since "benchmark" tests can easily be filtered in the UI, there's no need to append a qualifier to these tests, unless there's any one benchmark test that is particularly interesting.

**Comment by juan-fernandez** [comment]
there are already roughly 1000 tests with 3 executions each. If we add more, isn't it going to be too slow to run? @borjaburgos

**Comment by juan-fernandez** [comment]
btw we have no benchmark tests in js

**Comment by borjaburgos** [comment]
Ok, how about making the distribution better without adding new tests? 
<img width="1111" alt="image" src="https://user-images.githubusercontent.com/3640206/78091587-4c924180-739b-11ea-8826-a0144460ddd0.png">

May be make some of the unit tests taking micro-seconds be a little slower. 

If it's too much work, disregard this. Not *super* important.

**Comment by juan-fernandez** [comment]
I'll try but some of the e2e tests can take long due to slow responses from the backend, meaning the resolution of slower tests will be ruined.
